# @Author: guiguan
# @Date:   2017-10-18T02:34:24+11:00
# @Email:  root@guiguan.net
# @Last modified by:   guiguan
# @Last modified time: 2018-01-25T15:50:38+11:00
#
# dbKoda - a modern, open source code editor, for MongoDB.
# Copyright (C) 2017-2018 Southbank Software
#
# This file is part of dbKoda.
#
# dbKoda is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dbKoda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dbKoda.  If not, see <http://www.gnu.org/licenses/>.

environment:
  nodejs_version: "8.9.1"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

version: '{build}.{branch}'

image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

# cache:
#   - "%LOCALAPPDATA%\\Yarn"

clone_script:
  - cmd: |
      git clone -q --depth=3 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      cd %APPVEYOR_BUILD_FOLDER%
      git checkout -qf %APPVEYOR_REPO_COMMIT%
      git submodule update --init --recursive --recommend-shallow --remote

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - java -version
  - python --version

build_script:
  - echo test

after_build:
  - ps: Get-ChildItem .\dbkoda\dist\* -Include *.exe, *.yml, *.sha1 | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName dbkodaExe }

test: off

deploy:
  - provider: Environment
    name: beta

notifications:
  - provider: Slack
    incoming_webhook:
      secure: /h1lUK1IriL1d59h1effsQhgOHq0uWSt3s6/+eLmiHZfqwuWaDCJnZ/erxbK5ENdoyrKN34bgi1uioLJhOBqx+WPiecxLgkgCGdQPYbnhc4=
    channel: ci
