# @Author: guiguan
# @Date:   2017-10-18T02:34:24+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-10-18T11:37:54+11:00
#
# dbKoda - a modern, open source code editor, for MongoDB.
# Copyright (C) 2017-2018 Southbank Software
#
# This file is part of dbKoda.
#
# dbKoda is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# dbKoda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with dbKoda.  If not, see <http://www.gnu.org/licenses/>.

environment:
  nodejs_version: "8.9.1"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

version: '{build}.{branch}'

image: Visual Studio 2017

# cache:
#   - "%LOCALAPPDATA%\\Yarn"

clone_script:
  - ps: |
      git clone -q --depth=3 --branch=${env:APPVEYOR_REPO_BRANCH} https://github.com/${env:APPVEYOR_REPO_NAME}.git ${env:APPVEYOR_BUILD_FOLDER}
      cd ${env:APPVEYOR_BUILD_FOLDER}
      git checkout -qf ${env:APPVEYOR_REPO_COMMIT}
      #git submodule update --init --recursive --recommend-shallow --depth=1 --remote
      git submodule update --init --recursive --remote

install:
  - ps: Install-Product node $env:nodejs_version
  - java -version
  - python --version
  # - systeminfo

build_script:
  - yarn install --no-progress
  - yarn gulp build
  - ps: Get-ChildItem .\dbkoda\dist\*.exe | %{ certutil -hashfile $_.FullName SHA1 > "$($_.FullName).sha1" }
  - yarn gulp addVersionSuffixToBuildArtifact

after_build:
  - ps: Get-ChildItem .\dbkoda\dist\* -Include *.exe, *.yml, *.sha1 | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName dbkodaExe }

test: off

deploy:
  - provider: Environment
    name: beta
